# Generated by Django 2.1.5 on 2023-05-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_todos_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
